### ISSUE TITLE
Sending build context to Docker daemon VERY slow

### ISSUE THREAD

**Issue by brikis98** [blinkreaction/boot2docker-vagrant#13] opened 2015-05-08 19:19 UTC
Has anyone else found that if you run `docker build` with the boot2docker-vagrant setup, the portion that says "Sending build context to Docker daemon" takes a VERY long time?

```
brikis98-pro:$ docker build .
Sending build context to Docker daemon 42.34 MB
```

The total size of the context is ~100MB, but it takes 5-10 min to get through that step. When I was using vanilla Boot2Docker, it only took a few seconds. 

Any ideas what could cause that?

**Comment by brikis98** [comment] 2015-05-11 01:18
OK, I think I've found the problem. I used [speedtest-cli](https://github.com/sivel/speedtest-cli) to test the network performance of a Docker container running on [boot2docker-vagrant](https://github.com/blinkreaction/boot2docker-vagrant):

```
> docker run -it --rm ubuntu:14.04 bash
root@52386ba8b6b0:/# ./speedtest-cli  
[...]
Testing download speed........................................
Download: 11.36 Mbit/s
Testing upload speed..................................................
Upload: 0.00 Mbit/s
```

So my upload speed is so bad that it can't even be measured. Anyone know why? Is there some Vagrant setting I'm missing? I found some of the typical responses about Vagrant network slowness, but they didn't help:

``` ruby
config.vm.provider "virtualbox" do |v|
  v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]    
end
```

Any ideas?

**Comment by brikis98** [comment] 2015-05-11 01:35
I found a fix in [this superuser discussion](http://superuser.com/questions/850357/how-to-fix-extremely-slow-virtualbox-network-download-speed):

``` ruby
config.vm.provider "virtualbox" do |v|
  v.customize ["modifyvm", :id, "--nictype1", "virtio"]
end
```

Once I added this setting to my Vagrantfile, the upload speed on the Docker container matched that of my host OS, and the "Sending build context to Docker daemon" step runs very quickly now.

**Comment by lmakarov** [comment] 2015-05-13 16:28
@brikis98 great find!

The issue is the adapter type (intel) that VirtualBox is using by default.
boot2docker-cli/docker-machine does set the adapter type to `virtio` (`Paravirtualized Network` in VBox GUI) when it provisions a boot2docker VirtualBox VM.
The base box template I'm using does not do this.

I will modify the template to use `virtio` for all network interfaces.
In the mean time the workaround you posted does the trick. Thanks!

**Comment by matthayes** [comment] 2015-05-13 20:13
I wonder if this explains why loading images using `docker load -i blah.tar` is so slow for me.  When using boot2docker an image was loading easily within 20-30 seconds.  With boot2docker-vagrant it is so slow I'm not sure whether it is even doing anything.  I gave up waiting for it to complete.  Something else I noticed is that the CPU usage of VirtualBox during this time is around 2%, where normally it is high when using boot2docker during an image load.

**Comment by lmakarov** [comment] 2015-06-18 20:00
Resolved in https://github.com/blinkreaction/boot2docker-vagrant/commit/ef09ddddcb0488a8a08fa20d268782bc52cebd67
Released in [v0.13.0](https://github.com/blinkreaction/boot2docker-vagrant/releases/tag/v0.13.0)

**Closed as completed by lmakarov** 2015-06-18 20:00 UTC

**Comment by 34code** [comment] 2016-04-24 06:58
This is happening again after virtualbox upgrade with new docker-toolbox package -- making life super slow

**Comment by lmakarov** [comment] 2016-04-25 14:40
@34code what do you mean `new docker-toolbox package`?

Please run the following and post here

```
$ VBoxManage --version
$ vagrant --version
$ cat <path/to>/Vagrantfile | grep box_version
$ env | grep DOCKER
$ docker version
```

**Comment by 34code** [comment] 2016-04-30 18:46
I mean v1.11.1 here: https://github.com/docker/toolbox/releases
